### Use token to access API
GET  http://localhost:8070/api/user/test/getUser
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwaHVvY2JrMjIiLCJpYXQiOjE3NDI5ODAyMDcsImV4cCI6MTc0Mjk4MDMxNX0.Ty1FHCWyfW2TWgrROu3MVxzpNpognQQcuqKutcc7Yww
###
GET  http://localhost:8070/api/user/test
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwaHVvY2JrMjIiLCJpYXQiOjE3NDI5ODAyMDcsImV4cCI6MTc0Mjk4MDMxNX0.Ty1FHCWyfW2TWgrROu3MVxzpNpognQQcuqKutcc7Yww
###FACE RECOGNITION
POST  http://localhost:8070/api/face_recognition
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImlhdCI6MTc0MzY1MzA3NSwiZXhwIjoxNzQzNjUzMTgzfQ.wrDmmQ-e_tnIC3nII6wB5kGSRnYrtN0unWefVbSIH_8

### USER LOGIN
POST  http://localhost:8070/api/user/login
Content-Type: application/json

{
  "username": "user1",
  "password": "user1"
}
###
POST  http://localhost:8070/api/voice-command
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwaHVvY2JrMjIiLCJpYXQiOjE3NDI5ODAyMDcsImV4cCI6MTc0Mjk4MDMxNX0.Ty1FHCWyfW2TWgrROu3MVxzpNpognQQcuqKutcc7Yww
Content-Type: application/json

{
  "command": "on the light"
}
###
POST  http://localhost:8070/api/home/add
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwaHVvY2JrMjIiLCJpYXQiOjE3NDMxNTUxMzcsImV4cCI6MTc0MzE1NTI0NX0.SixazRp18WBVmFVkvHKHSnuqGwz9_wSLKi6U9ZCLKmA
Content-Type: application/json

{
  "address":"HCM",
  "hometype":"apartment"
}
###
GET  http://localhost:8070/api/home/test
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwaHVvY2JrMjIiLCJpYXQiOjE3NDMxNTUzOTksImV4cCI6MTc0MzE1NTUwN30.71FU4Ihxk9F36X4gB4vU_6fFbY0hoT6kBL3sEGmEuWQ


### Employee
POST  http://localhost:8070/api/employee/adduser
Content-Type: application/json

{
  "username": "user1",
  "password": "user1",
  "homeId": "1"
}
### ADD USER
POST  http://localhost:8070/api/employee/addhome
Content-Type: application/json

{
  "address":"Dong nai",
  "hometype":"apartment"
}
### TEMPERATURE
GET http://localhost:8070/api/temperature/stream
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImlhdCI6MTc0Mzk1Mjg5NCwiZXhwIjoxNzQzOTUzMDAyfQ.07XqRfHwAc7TPWaj2jC6ZFVfkkE0sTGzV3T9Ik_uw68
Content-Type: application/json

{
  "deviceId": "device123"
}